spring:
  datasource:
    url: "jdbc:mysql://${DATABASE_IP:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_NAME:elypia}?autoReconnect=true\
                                                                                             &serverTimezone=UTC\
                                                                                             &sslMode=VERIFY_CA\
                                                                                             &trustCertificateKeyStoreUrl=file:${DATABASE_TRUST_KEYSTORE}\
                                                                                             &trustCertificateKeyStorePassword=${DATABASE_TRUST_KEYSTORE_PASSWORD}\
                                                                                             &clientCertificateKeyStoreUrl=file:${DATABASE_CLIENT_KEYSTORE}\
                                                                                             &clientCertificateKeyStorePassword=${DATABASE_CLIENT_KEYSTORE_PASSWORD}"
    username: ${DATABASE_USERNAME:elypia}
    password: ${DATABASE_PASSWORD}
google:
  recaptcha:
    enabled: true
    site-key: ${RECAPTCHA_SITE_KEY}
    secret-key: ${RECAPTCHA_SECRET_KEY}
stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLIC_KEY}
